name: PyPI Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    permissions:
      id-token: write # Разрешаем GitHub Actions запрашивать токен OIDC
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Debug dist
        run: ls -lah dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
